"""initial migration

Revision ID: 25b40f630a94
Revises:
Create Date: 2026-05-11 18:05:35.343067

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "25b40f630a94"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("linear_id", sa.String(), nullable=True),
        sa.Column("repository_url", sa.String(), nullable=False),
        sa.Column("repository_name", sa.String(), nullable=False),
        sa.Column("repository_owner", sa.String(), nullable=False),
        sa.Column("local_path", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="created", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("linear_task_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_mode", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("worktree_path", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="created", nullable=False),
        sa.Column("opencode_session_id", sa.String(), nullable=True),
        sa.Column("build_plan", sa.Text(), nullable=True),
        sa.Column("posted_to_linear", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_linear_task_id"), "sessions", ["linear_task_id"], unique=False)
    op.create_index(op.f("ix_sessions_opencode_session_id"), "sessions", ["opencode_session_id"], unique=False)
    op.create_index(op.f("ix_sessions_project_id"), "sessions", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_project_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_opencode_session_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_linear_task_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("projects")
    # ### end Alembic commands ###
